"""Build the current governed Cairns Council showcase package with Ollama."""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import sys
from pathlib import Path
from tempfile import TemporaryDirectory
from uuid import uuid4
from zipfile import ZipFile

from dotenv import load_dotenv

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))
load_dotenv(PROJECT_ROOT / ".env")

from scripts.evaluate_report_generation import run_scenario_with_artifacts  # noqa: E402
from scripts.release_paths import ReleasePathError, resolve_release_directory  # noqa: E402
from src.app_catalog import EXAMPLE_CASES  # noqa: E402
from src.audit import canonical_review_record, save_report_audit  # noqa: E402
from src.config import LLM_PROVIDER, MODEL_ENDPOINT_IS_LOCAL, model  # noqa: E402
from src.export_package import create_pilot_export_package  # noqa: E402
from src.export_register import build_export_register_snapshot  # noqa: E402
from src.governance import DRAFT_STATUS  # noqa: E402
from src.report_generation_quality import evaluate_governed_report  # noqa: E402
from src.report_grounding import evaluate_report_grounding  # noqa: E402
from src.report_template import append_human_signoff  # noqa: E402

DEFAULT_OUTPUT_DIR = resolve_release_directory(PROJECT_ROOT)[1]
DEFAULT_EXAMPLE = "Cairns Council pilot"
_SHA256 = re.compile(r"^[0-9a-f]{64}$")


def _sha256(payload):
    return hashlib.sha256(payload).hexdigest()


def _scenario_from_example(example_name):
    example = dict(EXAMPLE_CASES[example_name])
    return {
        "id": "showcase_cairns_council",
        "kind": "showcase",
        "location": example["location"],
        "audience": example["audience"],
        "scenario": example["scenario"],
        "concerns": example["concerns"],
        "timeframe": example["timeframe"],
        "extra_context": example["extra_context"],
        "expected_topic_groups": [],
        "forbidden_terms": [],
        "max_report_characters": 32000,
    }


def _review_record():
    return canonical_review_record(
        {
            "approval_status": DRAFT_STATUS,
            "reviewer_name": "",
            "reviewer_role": "",
            "review_date": "",
            "organisation_name": "",
            "review_notes": "",
        },
        default_status=DRAFT_STATUS,
    )


def _require_local_ollama_runtime():
    if LLM_PROVIDER != "ollama" or MODEL_ENDPOINT_IS_LOCAL is not True:
        raise RuntimeError("The current showcase must be generated by Ollama through a local loopback endpoint.")


def _validate_showcase_retrieval(row, analysis):
    knowledge = analysis.get("knowledge") if isinstance(analysis, dict) else None
    knowledge = knowledge if isinstance(knowledge, dict) else {}
    retrieved_chunks = knowledge.get("retrieved_chunks")
    retrieved_chunks = retrieved_chunks if isinstance(retrieved_chunks, list) else []
    row_chunk_count = row.get("retrieved_chunks")
    manifest_sha256 = str(knowledge.get("index_manifest_sha256") or "").lower()
    if (
        row.get("rag_behavior_passed") is not True
        or row.get("knowledge_status") != "ready"
        or knowledge.get("status") != "ready"
        or not isinstance(row_chunk_count, int)
        or isinstance(row_chunk_count, bool)
        or row_chunk_count < 1
        or not retrieved_chunks
        or _SHA256.fullmatch(manifest_sha256) is None
    ):
        raise RuntimeError(
            "The current showcase requires verified ready RAG, at least one retrieved chunk, "
            "a bound index manifest and a passing RAG-behaviour check."
        )
    return manifest_sha256


def build_showcase_sample(output_dir=None, *, example_name=DEFAULT_EXAMPLE):
    """Generate, audit, package and write one portfolio-safe governed sample."""

    if example_name not in EXAMPLE_CASES:
        raise ValueError(f"Unknown showcase example: {example_name}")
    _require_local_ollama_runtime()
    output_dir = Path(output_dir if output_dir is not None else resolve_release_directory(PROJECT_ROOT)[1]).resolve()
    example = EXAMPLE_CASES[example_name]
    scenario = _scenario_from_example(example_name)
    artifacts = run_scenario_with_artifacts(scenario)
    row = artifacts["row"]
    if row.get("governed_gate_passed") is not True:
        failures = row.get("blocking_failures") or []
        raise RuntimeError(f"Showcase generation failed the governed report gate: {failures}")

    analysis = artifacts["analysis"]
    rag_index_manifest_sha256 = _validate_showcase_retrieval(row, analysis)
    review_record = _review_record()
    report = append_human_signoff(artifacts["report"], review_record)
    quality = evaluate_governed_report(report, analysis)
    if quality.get("approval_gate", {}).get("passed") is not True:
        raise RuntimeError("The canonical showcase report failed after its deterministic sign-off was applied.")

    report_id = uuid4().hex
    report_version = 1
    model_boundary = "local_loopback" if MODEL_ENDPOINT_IS_LOCAL else "external"
    inputs = {
        "pilot_mode": example.get("pilot_mode"),
        "organisation_name": example.get("organisation_name"),
        "reviewer_name": "",
        "reviewer_role": example.get("reviewer_role"),
        "review_date": "",
        "review_notes": "",
        "report_status": DRAFT_STATUS,
        "location": scenario["location"],
        "audience": scenario["audience"],
        "scenario": scenario["scenario"],
        "concerns": scenario["concerns"],
        "timeframe": scenario["timeframe"],
        "extra_context": scenario["extra_context"],
    }
    package_context = {
        "pilot_mode": example.get("pilot_mode"),
        "organisation_name": example.get("organisation_name"),
        "location": scenario["location"],
        "audience": scenario["audience"],
        "scenario": scenario["scenario"],
        "report_status": DRAFT_STATUS,
        "selected_map_area": None,
        "model_provider": LLM_PROVIDER,
        "model_name": model,
        "model_endpoint_boundary": model_boundary,
        "report_id": report_id,
        "report_version": report_version,
    }
    register_snapshot = build_export_register_snapshot()
    grounding = evaluate_report_grounding(report, analysis)

    with TemporaryDirectory(prefix="bushfire-showcase-audit-") as audit_dir:
        previous_audit_dir = os.environ.get("BUSHFIRE_AUDIT_DIR")
        previous_sensitive_audit = os.environ.get("BUSHFIRE_AUDIT_INCLUDE_SENSITIVE_CONTENT")
        os.environ["BUSHFIRE_AUDIT_DIR"] = audit_dir
        os.environ["BUSHFIRE_AUDIT_INCLUDE_SENSITIVE_CONTENT"] = "false"
        try:
            audit_path = save_report_audit(
                {
                    "report_id": report_id,
                    "report_version": report_version,
                    "report_source": "generated",
                    "inputs": inputs,
                    "area_selection": None,
                    "analysis": analysis,
                    "quality": quality,
                    "grounding_evaluation": grounding,
                    "model_provider": LLM_PROVIDER,
                    "model_name": model,
                    "model_endpoint_boundary": model_boundary,
                    "external_model_acknowledged_at": None,
                    "report_status": DRAFT_STATUS,
                    "human_review": review_record,
                    "package_context": package_context,
                    "export_register_snapshot": register_snapshot,
                    "report_text": report,
                }
            )
            package = create_pilot_export_package(
                report,
                audit_path=audit_path,
                review_record=review_record,
                package_context=package_context,
                register_snapshot=register_snapshot,
                analysis=analysis,
            )
        finally:
            if previous_audit_dir is None:
                os.environ.pop("BUSHFIRE_AUDIT_DIR", None)
            else:
                os.environ["BUSHFIRE_AUDIT_DIR"] = previous_audit_dir
            if previous_sensitive_audit is None:
                os.environ.pop("BUSHFIRE_AUDIT_INCLUDE_SENSITIVE_CONTENT", None)
            else:
                os.environ["BUSHFIRE_AUDIT_INCLUDE_SENSITIVE_CONTENT"] = previous_sensitive_audit

    output_dir.mkdir(parents=True, exist_ok=True)
    markdown_path = output_dir / "cairns-council-report.md"
    pdf_path = output_dir / "cairns-council-report.pdf"
    docx_path = output_dir / "cairns-council-report.docx"
    package_path = output_dir / "cairns-council-pilot-package.zip"
    package_path.write_bytes(package["content"])

    with ZipFile(package_path) as archive:
        report_paths = {
            suffix: next(name for name in archive.namelist() if name.startswith("reports/") and name.endswith(suffix))
            for suffix in (".md", ".pdf", ".docx")
        }
        report_outputs = {
            ".md": markdown_path,
            ".pdf": pdf_path,
            ".docx": docx_path,
        }
        for suffix, path in report_outputs.items():
            path.write_bytes(archive.read(report_paths[suffix]))
        audit_record = json.loads(archive.read("governance/audit_record.json"))
        if "sensitive_payload" in audit_record or audit_record.get("privacy", {}).get("contains_full_report_text"):
            raise RuntimeError("The showcase package contains a sensitive audit payload and cannot be committed.")

    return {
        "example": example_name,
        "report_id": report_id,
        "generation_attempts": row.get("generation_attempts"),
        "quality_policy_version": quality.get("quality_policy_version"),
        "quality_policy_fingerprint": quality.get("quality_policy_fingerprint"),
        "governed_gate_passed": True,
        "rag_behavior_passed": True,
        "rag_index_manifest_sha256": rag_index_manifest_sha256,
        "model_provider": LLM_PROVIDER,
        "model_name": model,
        "model_endpoint_boundary": model_boundary,
        "files": {
            path.name: {"sha256": _sha256(path.read_bytes()), "size_bytes": path.stat().st_size}
            for path in (markdown_path, pdf_path, docx_path, package_path)
        },
    }


def main(argv: list[str] | None = None):
    parser = argparse.ArgumentParser(description=__doc__)
    output_group = parser.add_mutually_exclusive_group()
    output_group.add_argument(
        "--release-dir",
        type=Path,
        help="Repository-contained release directory (defaults to examples/v<project version>).",
    )
    output_group.add_argument(
        "--output-dir",
        type=Path,
        help="Legacy explicit output path; prefer --release-dir for committed release evidence.",
    )
    parser.add_argument(
        "--release-version",
        help="Release version used by the default release directory; defaults to project.version.",
    )
    parser.add_argument("--example", choices=sorted(EXAMPLE_CASES), default=DEFAULT_EXAMPLE)
    args = parser.parse_args(argv)
    if args.output_dir is not None:
        output_dir = args.output_dir
    else:
        try:
            _, output_dir = resolve_release_directory(
                PROJECT_ROOT,
                release_version=args.release_version,
                release_dir=args.release_dir,
            )
        except ReleasePathError as error:
            parser.error(str(error))
    result = build_showcase_sample(output_dir, example_name=args.example)
    print(json.dumps(result, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
