"""Shared governance constants and review-checklist helpers.

The checklist IDs are stable storage keys. Display labels may evolve without
changing the meaning of an existing review record.
"""

DRAFT_STATUS = "Draft - human review required"
NEEDS_REVISION_STATUS = "Needs revision"
REVIEWED_DRAFT_STATUS = "Reviewed draft"
APPROVED_STATUS = "Approved by organisation"
REPORT_STATUSES = (
    DRAFT_STATUS,
    NEEDS_REVISION_STATUS,
    REVIEWED_DRAFT_STATUS,
    APPROVED_STATUS,
)
REVIEWED_STATUSES = {REVIEWED_DRAFT_STATUS, APPROVED_STATUS}

HUMAN_REVIEW_CHECKLIST = (
    {
        "id": "geography_and_profile",
        "label": "Selected geography and community profile have been reviewed.",
    },
    {
        "id": "official_sources",
        "label": "Official source links have been checked by a human reviewer.",
    },
    {
        "id": "no_live_directions",
        "label": "No live warning, evacuation order, or fire ban has been generated by the app.",
    },
    {
        "id": "assembly_points",
        "label": "Candidate assembly points are marked as needing official/local confirmation.",
    },
    {
        "id": "draft_boundary",
        "label": "The report is treated as a draft until approved by the responsible organisation.",
    },
)


def build_review_checklist_snapshot(is_checked=None):
    """Return all canonical checklist items with a point-in-time checked state."""

    checker = is_checked or (lambda _item_id: False)
    return [
        {
            "id": item["id"],
            "label": item["label"],
            "checked": bool(checker(item["id"])),
        }
        for item in HUMAN_REVIEW_CHECKLIST
    ]


def is_review_checklist_complete(checklist):
    """Fail closed unless every canonical item appears exactly once and is checked."""

    if not isinstance(checklist, list) or len(checklist) != len(HUMAN_REVIEW_CHECKLIST):
        return False
    expected_ids = {item["id"] for item in HUMAN_REVIEW_CHECKLIST}
    observed = {}
    for item in checklist:
        if not isinstance(item, dict):
            return False
        item_id = item.get("id")
        if item_id in observed:
            return False
        observed[item_id] = item.get("checked") is True
    return set(observed) == expected_ids and all(observed.values())
