from datetime import datetime
import json
import os

import streamlit as st

from src.app_state import (
    get_active_analysis_location,
    get_active_map_selection_label,
    get_latest_assistant_text,
    is_welcome_message,
    save_latest_report,
)
from src.app_catalog import (
    EXAMPLE_CASES,
    SCENARIO_OPTIONS,
    TIMEFRAME_OPTIONS,
)
from src.report_workflow import (
    collect_review_record,
    generate_current_report as run_generate_current_report,
    get_package_context,
    update_latest_audit_review,
    update_latest_report_signoff as run_update_latest_report_signoff,
)
from src.session_store import INTERACTION_LOG_PATH, clear_conversation, initialize_state, persist_session_state
from src.ui.data_views import (
    render_data_register,
    render_data_status,
    render_licence_register,
    render_official_sources,
    render_official_status_panel,
)
from src.ui.demo_views import (
    render_demo_scenario_pack,
    render_government_pilot_brief,
    render_maturity_assessment,
    render_presentation_mode,
    render_usage_guide,
)
from src.ui.layout import render_header
from src.ui.map_views import render_coverage_analysis_tools
from src.ui.review_views import (
    render_agent_analysis_summary,
    render_human_review_checklist,
    render_pilot_export_package,
    render_report_quality_summary,
    render_reviewer_approval,
)
from src.ui.report_views import render_latest_report_preview, render_report_form
from src.ui.sidebar import render_sidebar
from src.ui.theme import apply_theme

try:
    import clipboard
except ImportError:
    clipboard = None


PILOT_MODE_OPTIONS = [
    "School Preparedness",
    "Council Community Preparedness",
    "Community Workshop Material",
]
REVIEW_CHECKLIST = [
    "Selected geography and community profile have been reviewed.",
    "Official source links have been checked by a human reviewer.",
    "No live warning, evacuation order, or fire ban has been generated by the app.",
    "Candidate assembly points are marked as needing official/local confirmation.",
    "The report is treated as a draft until approved by the responsible organisation.",
]
st.set_page_config(
    page_title="BushfireReadyGPT",
    page_icon="",
    layout="wide",
    initial_sidebar_state="expanded",
)

def initialize_form_defaults():
    defaults = {
        "form_location": "",
        "form_audience": "",
        "form_timeframe": TIMEFRAME_OPTIONS[0],
        "form_scenario": SCENARIO_OPTIONS[0],
        "form_concerns": [],
        "form_extra_context": "",
        "pilot_mode": PILOT_MODE_OPTIONS[0],
        "organisation_name": "",
        "reviewer_name": "",
        "reviewer_role": "Preparedness officer / responsible reviewer",
        "review_date": datetime.now().date(),
        "review_notes": "",
        "report_status": "Draft - human review required",
        "approval_reviewer_name": "",
        "approval_reviewer_role": "Preparedness officer / responsible reviewer",
        "approval_organisation_name": "",
        "approval_status": "Draft - human review required",
        "approval_review_date": datetime.now().date(),
        "approval_review_notes": "",
        "active_demo_scenario": "",
        "demo_generation_notice": "",
    }
    for key, value in defaults.items():
        if key not in st.session_state:
            st.session_state[key] = value


def load_example_case(case_name):
    example = EXAMPLE_CASES[case_name]
    st.session_state.form_location = example["location"]
    st.session_state.form_audience = example["audience"]
    st.session_state.form_timeframe = example["timeframe"]
    st.session_state.form_scenario = example["scenario"]
    st.session_state.form_concerns = example["concerns"]
    st.session_state.form_extra_context = example["extra_context"]
    st.session_state.pilot_mode = example.get("pilot_mode", PILOT_MODE_OPTIONS[0])
    st.session_state.organisation_name = example.get("organisation_name", "")
    st.session_state.reviewer_name = example.get("reviewer_name", "")
    st.session_state.reviewer_role = example.get("reviewer_role", "Preparedness officer / responsible reviewer")
    st.session_state.approval_organisation_name = st.session_state.organisation_name
    st.session_state.approval_reviewer_name = st.session_state.reviewer_name
    st.session_state.approval_reviewer_role = st.session_state.reviewer_role
    map_selection = example.get("map_selection")
    if map_selection:
        apply_map_selection(map_selection)


def apply_map_selection(map_selection):
    st.session_state.selected_map_area = dict(map_selection)
    st.session_state.map_state = map_selection.get("state", "")
    st.session_state.map_level = map_selection.get("level", "SA4")
    st.session_state.map_area = map_selection.get("area_name", "")
    st.session_state.map_search = ""


def load_demo_scenario(demo):
    load_example_case(demo["example_case"])
    st.session_state.active_demo_scenario = demo["title"]


def update_latest_report_signoff(review_record):
    return run_update_latest_report_signoff(review_record, is_welcome_message)


def generate_current_report():
    return run_generate_current_report(persist_session_state)


def on_copy_click(text):
    st.session_state.copied.append(text)
    if clipboard is not None:
        clipboard.copy(text)


def display_feedback(message, index, file):
    increment = 0
    if message["role"] == "assistant":
        st.button("Copy response", on_click=on_copy_click, args=(message["content"],), key=f"copy_{index}")
        with st.expander("Response note", expanded=False):
            note = st.text_area("Optional: record an issue or requested edit for this response", key=f"response_note_{index}", height=80)
            if note:
                message["note"] = note
        increment = 1
    message_save = {k: v for k, v in message.items() if k != "content"}
    message_save["content"] = message["content"] if isinstance(message["content"], str) else message["content"][0]
    file.write(json.dumps(message_save, ensure_ascii=False) + "\n")
    file.flush()
    return increment


def display_response(message, index=0, file=None):
    with st.chat_message(message["role"]):
        st.markdown(message["content"])
        return display_feedback(message, index, file)


def render_conversation_history():
    index = 0
    os.makedirs("chat_history", exist_ok=True)
    with open(INTERACTION_LOG_PATH, "w", encoding="utf-8") as file:
        with st.expander("Conversation History", expanded=False):
            for message in st.session_state.messages:
                index += display_response(message, index, file)


def render_workspace_tabs():
    st.markdown("### Mission Workspace")
    create_tab, review_tab, data_tab, demo_tab, readiness_tab = st.tabs(
        [
            "Create Report",
            "Review & Export",
            "Data & Map",
            "Demo Guide",
            "Readiness",
        ]
    )

    with create_tab:
        render_report_form(
            PILOT_MODE_OPTIONS,
            initialize_form_defaults,
            load_example_case,
            get_active_map_selection_label,
            generate_current_report,
        )
        render_latest_report_preview(
            get_latest_assistant_text,
            save_latest_report,
            collect_review_record,
            get_package_context,
        )

    with review_tab:
        render_agent_analysis_summary(get_active_map_selection_label)
        render_report_quality_summary()
        render_human_review_checklist(REVIEW_CHECKLIST)
        render_reviewer_approval(
            collect_review_record,
            update_latest_report_signoff,
            update_latest_audit_review,
            persist_session_state,
        )
        render_pilot_export_package(get_latest_assistant_text, collect_review_record, get_package_context)
        render_conversation_history()

    with data_tab:
        render_coverage_analysis_tools(get_active_analysis_location())
        render_official_status_panel()
        render_official_sources()
        render_data_status()
        render_data_register()
        render_licence_register()

    with demo_tab:
        render_demo_scenario_pack(load_demo_scenario, generate_current_report)
        render_presentation_mode()
        render_government_pilot_brief()
        render_usage_guide()

    with readiness_tab:
        render_maturity_assessment()


apply_theme()
render_sidebar(
    clear_conversation,
    get_latest_assistant_text,
    collect_review_record,
    get_package_context,
    save_latest_report,
)
render_header()
initialize_state()
render_workspace_tabs()

if user_prompt := st.chat_input("Enter an additional location, audience detail or edit request"):
    with st.chat_message("user"):
        st.markdown(user_prompt)
    st.session_state.messages.append({"role": "user", "content": user_prompt})

    with st.chat_message("assistant"):
        full_response = st.session_state.assistant.get_assistant_response(user_prompt)
        st.markdown(full_response)
        for viz in getattr(st.session_state.assistant, "pending_visualizations", []):
            st.plotly_chart(viz, use_container_width=True)
        st.session_state.assistant.pending_visualizations = []

    st.session_state.messages.append({"role": "assistant", "content": full_response})
    persist_session_state()
    st.rerun()
